export const allMaps = [
    {
        id:'0',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        buildingImg: 'sumanadasa',
        description: 'Sumanadasa Building is a historic landmark within the University of Moratuwa (UoM). It houses various academic departments and serves as a central hub for student activities and research endeavors.',
    },
    {
        id:'1',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Civil Building',
        floorName: '1st Floor',
        buildingImg: 'civil',
        description: 'Civil Building is an integral part of the University of Moratuwa (UoM), hosting classrooms, laboratories, and offices for the Civil Engineering department. It stands as a testament to UoM\'s commitment to excellence in engineering education.',
    },
    {
        id:'2',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Admin Building',
        floorName: '1st Floor',
        buildingImg: 'admin',
        description: 'Admin Building serves as the administrative center of the University of Moratuwa (UoM), housing offices responsible for the smooth operation of the institution. From student services to academic planning, this building plays a pivotal role in supporting UoM\'s mission.',
    },
    {
        id:'3',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Goda Canteen',
        floorName: '1st Floor',
        buildingImg: 'godaCanteen',
        description: 'Goda Canteen is a popular dining spot within the University of Moratuwa (UoM), offering a variety of delicious meals and refreshments to students, faculty, and visitors. It provides a vibrant social atmosphere and serves as a meeting point for the UoM community.',
    },
    {
        id:'4',
        buildingId: '0',
        floorId: '1',
        buildingName: 'IT Building',
        floorName: '1st Floor',
        buildingImg: 'it',
        description: 'IT Building houses state-of-the-art facilities for computer science and information technology departments at the University of Moratuwa (UoM). From advanced laboratories to collaborative spaces, it fosters innovation and technological advancement among students and researchers.',
    },
    {
        id:'5',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Mechanical Building',
        floorName: '1st Floor',
        buildingImg: 'mechanical',
        description: 'Mechanical Building is a cornerstone of engineering education at the University of Moratuwa (UoM), providing specialized facilities for mechanical engineering research and instruction. It embodies UoM\'s commitment to excellence in engineering disciplines.',
    },
    {
        id:'6',
        buildingId: '0',
        floorId: '1',
        buildingName: 'NA 1,2 Building',
        floorName: '1st Floor',
        buildingImg: 'naLecHall',
        description: 'NA 1,2 Building accommodates lecture halls and classrooms at the University of Moratuwa (UoM), facilitating the delivery of high-quality education across various academic disciplines. It serves as a space for intellectual exchange and academic growth.',
    },
]
