export const allMaps = [
    {
        id:'0',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        map: '../../assets/maps/indoorMap.png',
        description: 'Sumanadasa is a historic building nestled within the University of Moratuwa. It serves as a hub for academic pursuits, housing four prominent faculties:',
    },
    {
        id:'1',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        map: '../../assets/maps/indoorMap.png',
        description: 'Sumanadasa is a historic building nestled within the University of Moratuwa. It serves as a hub for academic pursuits, housing four prominent faculties:',
    },
    {
        id:'2',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        map: '../../assets/maps/indoorMap.png',
        description: 'Sumanadasa is a historic building nestled within the University of Moratuwa. It serves as a hub for academic pursuits, housing four prominent faculties:',
    },
    {
        id:'3',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        map: '../../assets/maps/indoorMap.png',
        description: 'Sumanadasa is a historic building nestled within the University of Moratuwa. It serves as a hub for academic pursuits, housing four prominent faculties:',
    },
    {
        id:'4',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        map: '../../assets/maps/indoorMap.png',
        description: 'Sumanadasa is a historic building nestled within the University of Moratuwa. It serves as a hub for academic pursuits, housing four prominent faculties:',
    },
    {
        id:'5',
        buildingId: '0',
        floorId: '1',
        buildingName: 'Sumanadasa Building',
        floorName: '1st Floor',
        map: '../../assets/maps/indoorMap.png',
        description: 'Sumanadasa is a historic building nestled within the University of Moratuwa. It serves as a hub for academic pursuits, housing four prominent faculties:',
    },
]